### ISSUE TITLE
Changing `plot_mainland` x-axis to time before present

### ISSUE THREAD

**Issue by joshwlambert** [joshwlambert/DAISIEmainland#63] opened 2022-01-18 17:07 UTC
@richelbilderbeek As I mentioned in issue #62 I think the best x-axis for the island and mainland plots would be time before present. Therefore would you be able to implement this for `plot_mainland`? I have made a few changes to the function which you can find on the joss branch.

**Comment by joshwlambert** [comment] 2022-01-18 17:07
![image](https://user-images.githubusercontent.com/46606402/149984517-eb9c338d-772e-49c4-a586-a9933127ba8e.png)

**Comment by richelbilderbeek** [comment] 2022-01-24 15:28
Hi @joshwlambert, sure, I can do that, Pull Request #65 is already closer to the image you show.

AFAICS, all I need to do is change the axis text now. Will do so now :-)

**Comment by richelbilderbeek** [comment] 2022-01-24 15:31
Reprex, situation before:

```r
test_that("minimal example use", {
  set.seed(
    1,
    kind = "Mersenne-Twister",
    normal.kind = "Inversion",
    sample.kind = "Rejection"
  )
  mainland <- sim_mainland(
    total_time = 1,
    m = 2,
    mainland_ex = 1
  )

  plot_mainland(mainland)
})
```

![Screenshot from 2022-01-24 16-31-11](https://user-images.githubusercontent.com/2098230/150812895-12d37d6e-abc7-43fb-948f-76b119f6c35d.png)

**Comment by richelbilderbeek** [comment] 2022-01-24 15:38
![Screenshot from 2022-01-24 16-31-11](https://user-images.githubusercontent.com/2098230/150814051-7ed458ef-3cb9-44c1-bbdf-cc0ad3b60fe9.png)

Hi @joshwlambert, is this correct; i.e., is this what you want?

**Comment by richelbilderbeek** [comment] 2022-01-24 17:33
More or less the answer I got from email: 

> Yes

**Comment by richelbilderbeek** [comment] 2022-01-24 17:42
Done:

![Screenshot from 2022-01-24 18-42-06](https://user-images.githubusercontent.com/2098230/150835710-c1e4b8b7-d465-4e74-a3b0-f6d6e83cc75b.png)

**Comment by richelbilderbeek** [comment] 2022-01-25 16:48
My work is done, waiting for the PR to be accepted ...

**Comment by richelbilderbeek** [comment] 2022-02-20 15:29
AFAICS, this has been done, as it was the cause of the incorrect plotting at #70 (which is now fixed). I suggest to close this Issue :+1:

**Closed** 2022-02-20 15:30 UTC
